def submission_fail() -> int:
    # TODO, for now fail_competition just throws a RuntimeError
    return 0
